version: '3.8'

services:
  db:
    image: postgres:16.1
    container_name: besttravel
    restart: always
    volumes:
      - ./db/sql/create_schema.sql:/docker-entrypoint-initdb.d/create_schema.sql
      - ./db/sql/data.sql:/docker-entrypoint-initdb.d/data.sql
    environment:
      - POSTGRES_DB=best_travel
      - POSTGRES_USER=camilog
      - POSTGRES_PASSWORD=123456789
    ports:
      - "5432:5432"

  cache-db:
    image: redis:7.2.3
    container_name: besttravel_cache
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --loglevel warning --requirepass camilog90

  document-db:
    image: mongo
    restart: always
    container_name: besttravel_users
    environment:
      MONGO_INITDB_ROOT_USERNAME: master
      MONGO_INITDB_ROOT_PASSWORD: camilog90
      MONGO_INITDB_DATABASE: users
    ports:
      - "27017:27017"
    volumes:
      - ./db/mongo/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
